name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Build"]
    types: ["completed"]

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log event data
        run: |
          echo "Event data: ${{ toJson(github.event) }}"

  publish:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'release' && github.event.workflow_run.action == 'published'
    permissions:
      id-token: write
    steps:
      - name: Log event data
        run: |
          echo "Event data: ${{ toJson(github.event) }}"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      #- name: Publish to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
